---
# file: roles/haproxy/tasks/config.yml
- name: Configuring HAproxy
  tags: [haproxy, haproxy-config]
  ansible.builtin.template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: "{{ haproxy_config }}"
    mode: "0640"
    # FIXME: below validate config file when system mode
    # need to find a way to validate in Docker mode
    # validate: "{{ haproxy_bin }} -f %s -c"
    validate: "{{ (haproxy_mode == 'system') | ternary(haproxy_bin ~ ' -f %s -c', omit) }}"
  notify: Reload haproxy
