---
# file: roles/haproxy/handlers/main.yml
- name: Restart haproxy
  ansible.builtin.service:
    name: "{{ haproxy_service }}"
    state: restarted
  when: haproxy_mode == "system" or haproxy_mode == "custom"

- name: Reload haproxy
  ansible.builtin.service:
    name: "{{ haproxy_service }}"
    state: reloaded
  when: haproxy_mode == "system" or haproxy_mode == "custom"
