---
# file: roles/haproxy/handlers/main.yml
- name: restart haproxy
  ansible.builtin.service:
    name: "{{ haproxy_service }}"
    state: restarted
  when: haproxy_mode == "system"

- name: reload haproxy
  ansible.builtin.service:
    name: "{{ haproxy_service }}"
    state: reloaded
  when: haproxy_mode == "system"
