---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  # https://wiki.debian.org/DebianReleases
  - name: debian12
    image: debian:12-slim
    command: sleep infinity
    groups: [Debian]
    privileged: true
  # https://wiki.debian.org/DebianReleases
  - name: debian11
    image: debian:11-slim
    command: sleep infinity
    groups: [Debian]
    privileged: true
  - name: debian10
    image: debian:10-slim
    command: sleep infinity
    groups: [Debian]
    privileged: true
  # https://rockylinux.org/
  - name: rockylinux8
    image: rockylinux:8
    command: /sbin/init
    groups: [RedHat]
    privileged: true
  - name: rockylinux9
    image: rockylinux:9
    command: /sbin/init
    groups: [RedHat]
    privileged: true
  # https://fedoraproject.org/wiki/Releases
  - name: fedora37
    image: fedora:37
    command: /sbin/init
    groups: [RedHat]
    privileged: true
  - name: fedora38
    image: fedora:38
    command: /sbin/init
    groups: [RedHat]
    privileged: true
  - name: fedora39
    image: fedora:39
    command: /sbin/init
    groups: [RedHat]
    privileged: true
  # https://wiki.ubuntu.com/Releases
  - name: ubuntu22.04
    image: ubuntu:22.04
    command: sleep infinity
    groups: [Debian]
    privileged: true
  - name: ubuntu20.04
    image: ubuntu:20.04
    command: sleep infinity
    groups: [Debian]
    privileged: true
  - name: ubuntu18.04
    image: ubuntu:18.04
    command: sleep infinity
    groups: [Debian]
    privileged: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      Debian:
        apache_pkg: apache2
        apache_service: apache2
        apache_ports: /etc/apache2/ports.conf
        apache_conf_d: /etc/apache2/conf-enabled
      RedHat:
        apache_pkg: httpd
        apache_service: httpd
        apache_ports: /etc/httpd/conf/httpd.conf
        apache_conf_d: /etc/httpd/conf.d
scenario:
  name: default
  test_sequence:
    - dependency
    # - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  options:
    v: true
